name 'cloudsmith-wordpress'
version '0.1.0'

author 'Cloudsmith Inc.'
license 'Apache License 2.0'
project_page ''
source ''
summary 'Wordpress blog'
description ''

dependency 'cloudsmith/apache2', '>=0.1.0'
dependency 'cloudsmith/augeas', '>=0.1.0'
dependency 'cloudsmith/mysql', '>=0.1.0'
dependency 'cloudsmith/php5', '>=0.1.0'
