name 'hlindberg-myblog'
version '0.0.0'

dependency 'cloudsmith/apache2', '>=0.1.0'
dependency 'cloudsmith/augeas', '>=0.1.0'
dependency 'cloudsmith/mysql', '>=0.1.0'
dependency 'cloudsmith/php5', '>=0.1.0'
dependency 'cloudsmith/wordpress', '>=0.1.0'
